### ISSUE TITLE
Importing views in mysite/urls.py

### ISSUE THREAD

**Issue by kristinriebe** [pathway/ed-questionnaire#1]
Thanks for supporting django-1.10!
Following the README for branch django-1.10, I got an error at the step:  
`python manage.py makemigrations`  
Error: `NameError: name 'generate_run' is not defined`  

This can be fixed by importing the needed views in the main site's urls.py, i.e. adding following lines to `mysite/urls.py`:

```
from questionnaire.views import generate_run, set_language
from questionnaire.page.views import page, langpage
```

So the complete (initial) mysite/urls.py looks like this:

**[mysite/urls.py]**
```
from django.conf.urls import include, url
from django.contrib import admin

from questionnaire.views import generate_run, set_language
from questionnaire.page.views import page, langpage

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    # questionnaire urls
    url(r'q/', include('questionnaire.urls')),
    
    url(r'^take/(?P<questionnaire_id>[0-9]+)/$', generate_run, name='generate_run'),
    url(r'^$', page, {'page_to_render' : 'index'}, name='page'),
    url(r'^(?P<lang>..)/(?P<page_to_trans>.*)\.html$', langpage, name='langpage'),
    url(r'^(?P<page_to_render>.*)\.html$', page, name='page'),
    url(r'^setlang/$', set_language, name='set_language'),
]
```

**Comment by pathway** [comment]
Fixed in https://github.com/pathway/ed-questionnaire/commit/c32ef2f71676918c7fbf421e9423544c39864eaa

Submitted PR to upstream repo at https://github.com/eldest-daughter/ed-questionnaire/pull/22
